version: '3'
services:
  movies:
    image: prasadyadav99/moviesrepopaytm:latest
    ports:
      - "80:80"
    deploy:
      replicas: 3
  train:
    image: prasadyadav99/trainrepopaytm:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  dth:
    image: prasadyadav99/dthrepopaytm:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  recharge:
    image: prasadyadav99/rechargerepopaytm:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
